execute_process(
  COMMAND "${PYTHON}" "${CMAKE_CURRENT_LIST_DIR}/espidf_pre.py" "${CMAKE_SOURCE_DIR}"
  RESULT_VARIABLE STICKS3_VIRTUAL_PATCH_RESULT
  OUTPUT_VARIABLE STICKS3_VIRTUAL_PATCH_OUTPUT
  ERROR_VARIABLE STICKS3_VIRTUAL_PATCH_ERROR
)
if(NOT STICKS3_VIRTUAL_PATCH_RESULT EQUAL 0)
  message(FATAL_ERROR "StickS3 virtual-board patch failed: ${STICKS3_VIRTUAL_PATCH_ERROR}")
endif()
message(STATUS "${STICKS3_VIRTUAL_PATCH_OUTPUT}")
add_compile_definitions(STICKS3_VIRTUAL_DEVICE)
add_link_options("-Wl,--wrap=adc_calc_hw_calibration_code")
add_link_options("-Wl,--wrap=spi_bus_initialize")
add_link_options("-Wl,--wrap=esp_lcd_new_panel_io_spi")
add_link_options("-Wl,--wrap=esp_lcd_new_panel_st7789")
add_link_options("-Wl,--wrap=esp_lcd_panel_io_register_event_callbacks")
add_link_options("-Wl,--wrap=esp_lcd_panel_reset")
add_link_options("-Wl,--wrap=esp_lcd_panel_init")
add_link_options("-Wl,--wrap=esp_lcd_panel_invert_color")
add_link_options("-Wl,--wrap=esp_lcd_panel_swap_xy")
add_link_options("-Wl,--wrap=esp_lcd_panel_mirror")
add_link_options("-Wl,--wrap=esp_lcd_panel_set_gap")
add_link_options("-Wl,--wrap=esp_lcd_panel_disp_on_off")
add_link_options("-Wl,--wrap=esp_lcd_panel_draw_bitmap")
add_link_options("-Wl,--wrap=gpio_get_level")
add_link_options("-Wl,--wrap=vibe_board_init_power")
add_link_options("-Wl,--wrap=vibe_board_imu_init")
add_link_options("-Wl,--wrap=vibe_board_accel_read")
add_link_options("-Wl,--wrap=vibe_board_battery_level")
add_link_options("-Wl,--wrap=vibe_board_battery_charging")
add_link_options("-Wl,--wrap=vibe_board_usb_powered")
add_link_options("-Wl,--wrap=vibe_board_speaker_set_enabled")
add_link_options("-Wl,--wrap=esp_http_client_init")
add_link_options("-Wl,--wrap=esp_http_client_set_url")
add_link_options("-Wl,--wrap=esp_http_client_set_method")
add_link_options("-Wl,--wrap=esp_http_client_set_header")
add_link_options("-Wl,--wrap=esp_http_client_set_post_field")
add_link_options("-Wl,--wrap=esp_http_client_perform")
add_link_options("-Wl,--wrap=esp_http_client_get_status_code")
add_link_options("-Wl,--wrap=esp_http_client_cleanup")
include_directories("${CMAKE_SOURCE_DIR}/components/sticks3_virtual_board")
